### ISSUE TITLE
cascading directory config

### ISSUE THREAD

**Issue by Xiaoy312** [Xiaoy312/VsLauncher#3]
extra config to override app behaviors (for/when under) specific directory
syntax:
```yml
# applicable to current directory and under
config1: value1

"absolute-path--OR--relative-path":
  # applicable to that path and under
  # the absolute-path has to be nested under the directory of this file (to be discoverable)
  config1: value2
```
this file can be placed at the execution directory or above (same way as Directory.Build.props):
> For example, if your $(MSBuildProjectFullPath) was c:\users\username\code\test\case1, MSBuild would start searching there and then search the directory structure upward until it located a Directory.Build.props file, as in the following directory structure.
> ```
> c:\users\username\code\test\case1
> c:\users\username\code\test
> c:\users\username\code
> c:\users\username
> c:\users
> c:\
> ```
> -- https://learn.microsoft.com/en-us/visualstudio/msbuild/customize-your-build?view=vs-2022#search-scope

^ except, we dont stop at the first, but keeps going...

to-clarify: merge rules?
